### ISSUE TITLE
Widget for Life Expectancy

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/city-indicators#11]
We're missing one widget which is for Life Expectancy.

## Tasks

* [x] add widget `life-expectancy.json` in https://github.com/datahq/city-indicators/tree/master/widgets
* [x] write Vega specification where we compare life expectancy in London versus UK (male and female) - see graph on https://data.london.gov.uk/
  * [x] use vega online tool here - https://vega.github.io/editor/#/examples/vega/line-chart but refer to our example here - https://github.com/datahq/city-indicators/blob/master/widgets/housing.json#L14-L192 - but keep in mind that you need to put "values" array in online editor

**Comment by anuveyatsu** [comment]
FIXED
